EVALUATE
VAR BranchPerformanceRows =
    SUMMARIZECOLUMNS(
        'branches'[Branch_Name],
        FILTER(ALL('sales_data'[IsKulbardi]), 'sales_data'[IsKulbardi] = FALSE()),
        FILTER(ALL('sales_data'[ExcludedFromSales]), 'sales_data'[ExcludedFromSales] = 0),
        "TotalSales",
            CALCULATE(
                SUM('sales_data'[Sale_val]),
                ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
            ),
        "TotalCOGS",
            CALCULATE(
                SUM('sales_data'[Cogs]),
                ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
            )
    )
VAR DisplayRows =
    SELECTCOLUMNS(
        FILTER(
            BranchPerformanceRows,
            NOT ISBLANK('branches'[Branch_Name])
                && NOT ISBLANK([TotalSales])
                && [TotalSales] <> 0
        ),
        "BranchName", 'branches'[Branch_Name],
        "TotalSales", [TotalSales],
        "MarginPct", DIVIDE([TotalSales] - [TotalCOGS], [TotalSales])
    )
RETURN
DisplayRows
ORDER BY [TotalSales] DESC, [BranchName] ASC
