EVALUATE
SELECTCOLUMNS(
    ADDCOLUMNS(
        'customers',
        "CustomerID", 'customers'[ID],
        "CustomerName", 'customers'[Customer_Name],
        "LTV", COALESCE('customers'[Customer_AvaliableCredit], 0),
        "AccountStatus", 'customers'[Customer_AccountStatus],
        "ChurnScore",
            SWITCH(
                TRUE(),
                'customers'[Customer_AccountStatus] = TRUE(), 100,
                COALESCE('customers'[Customer_AvaliableCredit], 0) < 100, 80,
                COALESCE('customers'[Customer_AvaliableCredit], 0) < 1000, 50,
                COALESCE('customers'[Customer_AvaliableCredit], 0) < 10000, 20,
                10
            )
    ),
    "CustomerID", [CustomerID],
    "CustomerName", [CustomerName],
    "LTV", [LTV],
    "AccountStatus", [AccountStatus],
    "ChurnScore", [ChurnScore],
    "RiskSegment",
        SWITCH(
            TRUE(),
            [ChurnScore] >= 80, "High",
            [ChurnScore] >= 40, "Medium",
            "Low"
        )
)
