EVALUATE
VAR WithLTV =
    ADDCOLUMNS(
        'customers',
        "CustomerID", 'customers'[ID],
        "CustomerName", 'customers'[Customer_Name],
        "LTV", COALESCE('customers'[Customer_AvaliableCredit], 0)
    )
RETURN
SELECTCOLUMNS(
    WithLTV,
    "CustomerID", [CustomerID],
    "CustomerName", [CustomerName],
    "LTV", [LTV],
    "LTVBucket",
        SWITCH(
            TRUE(),
            [LTV] < 100, "<100",
            [LTV] < 1000, "100-999",
            [LTV] < 10000, "1k-9.9k",
            "10k+"
        )
)
