EVALUATE
VAR AnchorDate =
    CALCULATE(
        MAX('sales_data'[Invoice_Date]),
        REMOVEFILTERS()
    )
VAR FiscalYearStart =
    DATE(
        IF(MONTH(AnchorDate) >= 7, YEAR(AnchorDate), YEAR(AnchorDate) - 1),
        7,
        1
    )
VAR CurrentFyDates =
    FILTER(
        ALL('calendar'[CalendarDate]),
        'calendar'[CalendarDate] >= FiscalYearStart
            && 'calendar'[CalendarDate] <= AnchorDate
    )
VAR MonthlySales =
    SUMMARIZECOLUMNS(
        'calendar'[Year],
        'calendar'[MonthNum],
        'calendar'[Month MMM],
        CurrentFyDates,
        FILTER(ALL('sales_data'[IsKulbardi]), 'sales_data'[IsKulbardi] = FALSE()),
        FILTER(ALL('sales_data'[ExcludedFromSales]), 'sales_data'[ExcludedFromSales] = 0),
        "TotalSales",
            CALCULATE(
                SUM('sales_data'[Sale_val]),
                ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
            )
    )
RETURN
SELECTCOLUMNS(
    MonthlySales,
    "Year", 'calendar'[Year],
    "MonthNum", 'calendar'[MonthNum],
    "FiscalMonthIndex", MOD('calendar'[MonthNum] + 5, 12) + 1,
    "MonthLabel", 'calendar'[Month MMM] & " " & FORMAT('calendar'[Year], "0000"),
    "TotalSales", COALESCE([TotalSales], 0)
)
ORDER BY [Year] ASC, [MonthNum] ASC
