EVALUATE
VAR AnchorDate =
    CALCULATE(
        MAX('sales_data'[Invoice_Date]),
        'sales_data'[IsKulbardi] = FALSE(),
        'sales_data'[ExcludedFromSales] = 0,
        FILTER(
            'sales_data',
            ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
        )
    )
VAR FiscalYearStart =
    DATE(
        IF(MONTH(AnchorDate) >= 7, YEAR(AnchorDate), YEAR(AnchorDate) - 1),
        7,
        1
    )
VAR CurrentFyDates =
    FILTER(
        ALL('calendar'[CalendarDate]),
        'calendar'[CalendarDate] >= FiscalYearStart
            && 'calendar'[CalendarDate] <= AnchorDate
    )
VAR BranchSales =
    ADDCOLUMNS(
        SUMMARIZECOLUMNS('branches'[Branch_Name]),
        "TotalSales",
            CALCULATE(
                SUM('sales_data'[Sale_val]),
                CurrentFyDates,
                'sales_data'[IsKulbardi] = FALSE(),
                'sales_data'[ExcludedFromSales] = 0,
                FILTER(
                    'sales_data',
                    ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
                )
            )
    )
VAR RankedBranches =
    TOPN(
        50,
        FILTER(
            BranchSales,
            NOT ISBLANK('branches'[Branch_Name])
                && NOT ISBLANK([TotalSales])
                && [TotalSales] <> 0
        ),
        [TotalSales], DESC,
        'branches'[Branch_Name], ASC
    )
RETURN
SELECTCOLUMNS(
    RankedBranches,
    "BranchName", 'branches'[Branch_Name],
    "TotalSales", [TotalSales]
)
ORDER BY [TotalSales] DESC, [BranchName] ASC
