EVALUATE
VAR AnchorDate =
    CALCULATE(
        MAX('sales_data'[Invoice_Date]),
        REMOVEFILTERS()
    )
VAR FiscalYearStart =
    DATE(
        IF(MONTH(AnchorDate) >= 7, YEAR(AnchorDate), YEAR(AnchorDate) - 1),
        7,
        1
    )
VAR CurrentFyDates =
    FILTER(
        ALL('calendar'[CalendarDate]),
        'calendar'[CalendarDate] >= FiscalYearStart
            && 'calendar'[CalendarDate] <= AnchorDate
    )
VAR BranchSales =
    SUMMARIZECOLUMNS(
        'branches'[Branch_Name],
        CurrentFyDates,
        FILTER(ALL('sales_data'[IsKulbardi]), 'sales_data'[IsKulbardi] = FALSE()),
        FILTER(ALL('sales_data'[ExcludedFromSales]), 'sales_data'[ExcludedFromSales] = 0),
        "TotalSales",
            CALCULATE(
                SUM('sales_data'[Sale_val]),
                ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
            )
    )
VAR RankedBranches =
    TOPN(
        50,
        FILTER(
            BranchSales,
            NOT ISBLANK('branches'[Branch_Name])
                && NOT ISBLANK([TotalSales])
                && [TotalSales] <> 0
        ),
        [TotalSales], DESC,
        'branches'[Branch_Name], ASC
    )
RETURN
SELECTCOLUMNS(
    RankedBranches,
    "BranchName", 'branches'[Branch_Name],
    "TotalSales", [TotalSales]
)
ORDER BY [TotalSales] DESC, [BranchName] ASC
