EVALUATE
VAR AnchorDate =
    CALCULATE(
        MAX('sales_data'[Invoice_Date]),
        REMOVEFILTERS()
    )
VAR FiscalYearStart =
    DATE(
        IF(MONTH(AnchorDate) >= 7, YEAR(AnchorDate), YEAR(AnchorDate) - 1),
        7,
        1
    )
VAR PriorYearFiscalYearStart = EDATE(FiscalYearStart, -12)
VAR PriorYearAnchorDate = EDATE(AnchorDate, -12)
VAR CurrentFyDates =
    FILTER(
        ALL('calendar'[CalendarDate]),
        'calendar'[CalendarDate] >= FiscalYearStart
            && 'calendar'[CalendarDate] <= AnchorDate
    )
VAR PriorFytdDates =
    FILTER(
        ALL('calendar'[CalendarDate]),
        'calendar'[CalendarDate] >= PriorYearFiscalYearStart
            && 'calendar'[CalendarDate] <= PriorYearAnchorDate
    )
VAR TotalSalesFYTD =
    CALCULATE(
        SUM('sales_data'[Sale_val]),
        CurrentFyDates,
        'sales_data'[IsKulbardi] = FALSE(),
        'sales_data'[ExcludedFromSales] = 0,
        ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
    )
VAR TotalCogsFYTD =
    CALCULATE(
        SUM('sales_data'[Cogs]),
        CurrentFyDates,
        'sales_data'[IsKulbardi] = FALSE(),
        'sales_data'[ExcludedFromSales] = 0,
        ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
    )
VAR GrossProfitFYTD = TotalSalesFYTD - TotalCogsFYTD
VAR MarginPctFYTD = DIVIDE(GrossProfitFYTD, TotalSalesFYTD)
VAR PriorYearSalesFYTD =
    CALCULATE(
        SUM('sales_data'[Sale_val]),
        PriorFytdDates,
        'sales_data'[IsKulbardi] = FALSE(),
        'sales_data'[ExcludedFromSales] = 0,
        ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
    )
VAR SalesGrowthVsPY =
    DIVIDE(TotalSalesFYTD - PriorYearSalesFYTD, PriorYearSalesFYTD)
VAR ActiveCustomers =
    CALCULATE(
        COUNTROWS('customers'),
        FILTER(
            ALL('customers'),
            'customers'[Customer_AccountStatus] = TRUE()
        )
    )
RETURN
ROW(
    "TotalSalesFYTD", COALESCE(TotalSalesFYTD, 0),
    "GrossProfitFYTD", COALESCE(GrossProfitFYTD, 0),
    "MarginPctFYTD", MarginPctFYTD,
    "ActiveCustomers", COALESCE(ActiveCustomers, 0),
    "SalesGrowthVsPY", SalesGrowthVsPY
)
