EVALUATE
VAR AnchorDate =
    CALCULATE(
        MAX('sales_data'[Invoice_Date]),
        REMOVEFILTERS('calendar'),
        'sales_data'[IsKulbardi] = FALSE(),
        'sales_data'[ExcludedFromSales] = 0,
        FILTER(
            ALL('sales_data'[LineType]),
            ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
        )
    )
VAR FiscalYearStart =
    DATE(
        IF(MONTH(AnchorDate) >= 7, YEAR(AnchorDate), YEAR(AnchorDate) - 1),
        7,
        1
    )
VAR CurrentFyDates =
    FILTER(
        ALL('calendar'),
        'calendar'[CalendarDate] >= FiscalYearStart
            && 'calendar'[CalendarDate] <= AnchorDate
    )
VAR CustomerSales =
    SUMMARIZECOLUMNS(
        'customers'[Customer_Company],
        CurrentFyDates,
        "TotalSales", [Total Sales]
    )
VAR TopCustomers =
    TOPN(
        10,
        FILTER(CustomerSales, NOT ISBLANK([TotalSales]) && [TotalSales] <> 0),
        [TotalSales], DESC,
        'customers'[Customer_Company], ASC
    )
RETURN
SELECTCOLUMNS(
    TopCustomers,
    "CustomerCompany", 'customers'[Customer_Company],
    "TotalSales", [TotalSales]
)
ORDER BY [TotalSales] DESC, [CustomerCompany] ASC
