EVALUATE
VAR AnchorDate =
    CALCULATE(
        MAX('sales_data'[Invoice_Date]),
        REMOVEFILTERS()
    )
VAR FiscalYearStart =
    DATE(
        IF(MONTH(AnchorDate) >= 7, YEAR(AnchorDate), YEAR(AnchorDate) - 1),
        7,
        1
    )
VAR CurrentFyDates =
    FILTER(
        ALL('calendar'[CalendarDate]),
        'calendar'[CalendarDate] >= FiscalYearStart
            && 'calendar'[CalendarDate] <= AnchorDate
    )
VAR CustomerSales =
    SUMMARIZECOLUMNS(
        'customers'[Customer_Company],
        CurrentFyDates,
        FILTER(ALL('sales_data'[IsKulbardi]), 'sales_data'[IsKulbardi] = FALSE()),
        FILTER(ALL('sales_data'[ExcludedFromSales]), 'sales_data'[ExcludedFromSales] = 0),
        "TotalSales",
            CALCULATE(
                SUM('sales_data'[Sale_val]),
                ISBLANK('sales_data'[LineType]) || 'sales_data'[LineType] <> "KCOMP"
            )
    )
VAR TopCustomers =
    TOPN(
        10,
        FILTER(
            CustomerSales,
            NOT ISBLANK('customers'[Customer_Company])
                && NOT ISBLANK([TotalSales])
                && [TotalSales] <> 0
        ),
        [TotalSales], DESC,
        'customers'[Customer_Company], ASC
    )
RETURN
SELECTCOLUMNS(
    TopCustomers,
    "CustomerCompany", 'customers'[Customer_Company],
    "TotalSales", [TotalSales]
)
ORDER BY [TotalSales] DESC, [CustomerCompany] ASC
